[features]
seeds = false
skip-lint = false
[programs.localnet]
robot_x = "DurEqjii3an6iHe6jXhBcjwv5gKozyRry67rHne7oejJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/xxxx/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
